apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: k8s-ecoysystem-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heapster
  namespace: k8s-ecoysystem-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      task: monitoring
      k8s-app: heapster
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: justmine/heapster-amd64:v1.4.2
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:http://registry.geekbuy.cn:8080?inClusterConfig=false&kubeletHttps=true&kubeletPort=10250&useServiceAccount=true&auth=
        - --sink=influxdb:http://registry.geekbuy.cn:31271
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: k8s-ecoysystem-apps
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster
