version: '3'

services:
  healthchecks.api:
    image: healthchecksapi:v1.5
    build:
      context: .
      dockerfile: src/HealthChecks.Api/Dockerfile

  helloworld.api:
    image: helloworldapi:v1.0
    build:
      context: .
      dockerfile: src/HelloWorld.Api/Dockerfile

