apiVersion: apps/v1  
kind: Deployment
metadata:
  name: elasticsearch-geekbuying-light
  namespace: geekbuying-light-addons
spec:
  selector:
    matchLabels:
     component: elasticsearch
     role: geekbuying-light
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: geekbuying-light
      name: elasticsearch-geekbuying-light
    spec:
      nodeSelector:
        node-role.gkb.k8s/master: "106"
      containers:
      - name: elasticsearch-geekbuying-light
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:
        - name: cluster.name
          value: "elasticsearch-geekbuying-light"
        - name: xpack.security.enabled
          value: "false"
        ports:
        - containerPort: 9200
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        hostPath:
          path: /root/geekbuying/elasticsearch/geekbuyinglight
          type: DirectoryOrCreate