apiVersion: v1
kind: Service
metadata:
  namespace: geekbuying-light-addons
  labels:
    name: sentinel
    role: service
  name: redis-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-sentinel: "true"