apiVersion: v1
kind: Service
metadata:
  namespace: geekbuying-light-addons
  name: redis-master
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 32005
  selector:
    name: redis
    role: master