apiVersion: v1
kind: Service
metadata:
  name: nginx-hosted-exceptionless-ui
  namespace: k8s-ecoysystem-apps
spec:
  type: NodePort
  selector:
    app: nginx-hosted-exceptionless-ui
  ports:
  - nodePort: 32003
    port: 80
    targetPort: 80
