apiVersion: v1
kind: Service
metadata:
  namespace: geekbuying-light-addons
  name: elasticsearch-exceptionless
  labels:
    component: elasticsearch
    role: exceptionless
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: exceptionless
  ports:
  - name: http
    nodePort: 32008
    port: 9200
    protocol: TCP