apiVersion: v1
kind: Pod
metadata: 
  name: podwithsecreteinenv
spec: 
  containers: 
  - name: podwithsecreteinenv
    image: busybox
    args: 
      - /bin/sh
      - -c
      - sleep 10; touch /tmp/healthy; sleep 30000
    env:
      - name: SECRET_USERNAME
        valueFrom: 
          configMapKeyRef:
            name: myconfigmap
            key: config1
      - name: SECRET_PASSWORD
        valueFrom: 
          configMapKeyRef:
            name: myconfigmap
            key: config2
