apiVersion: v1
kind: ConfigMap
metadata:
  namespace: k8s-ecoysystem-apps
  name: helloworldapi-appsetting
  labels:
    app: helloworldapi  
data:
  EventBus: kafkamq
  MySqlConStr: Server=sql-data;Initial Catalog=db;User Id=sa;Password=Pass@word;
  Version: 0.1.0
  Logging: 
    IncludeScopes=false
    Debug: