apiVersion: v1
kind: Service
metadata:
  name: helloworldapi
  namespace: k8s-ecoysystem-apps
spec:
  type: NodePort
  selector:
    app: helloworldapi
  ports:
  - nodePort: 32001
    port: 80
    targetPort: 80
