apiVersion: apps/v1  
kind: Deployment
metadata:
  name: helloworldapi
  namespace: k8s-ecoysystem-apps
spec:
  selector:
    matchLabels:
      app: helloworldapi
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworldapi
      namespace: k8s-ecoysystem-apps
    spec:
      imagePullSecrets:
      - name: registry-key
      containers:
      - name: helloworldapi
        image: registry.geekbuy.cn/justmine/helloworldapi:v2.2
        ports:
        - containerPort: 80