apiVersion: apps/v1  
kind: Deployment
metadata:
  name: helloworldapi
  namespace: k8s-ecoysystem-apps
spec:
  selector:
    matchLabels:
      app: helloworldapi
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworldapi
      namespace: k8s-ecoysystem-apps
    spec:
      containers:
      - name: helloworldapi
        image: justmine/helloworldapi:v1.0
        ports:
        - containerPort: 80