apiVersion: apps/v1  
kind: Deployment
metadata:
  name: helloworldapi
  namespace: k8s-ecoysystem-apps
spec:
  selector:
    matchLabels:
      app: helloworldapi
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworldapi
      namespace: k8s-ecoysystem-apps
    spec:
      imagePullSecrets:
      - name: registry-key
      containers:
      - name: helloworldapi
        image: registry.wuling.com/justmine/helloworld.api:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        volumeMounts:
        - name: appsetting
          mountPath: "/configrations"
      volumes:
      - name: appsetting
        hostPath:
          path: /root/geekbuying/helloworldapi/configrations
          type: DirectoryOrCreate