apiVersion: apps/v1  
kind: Deployment
metadata:
  name: helloworldapi
  namespace: k8s-ecoysystem-apps
spec:
  selector:
    matchLabels:
      app: helloworldapi
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworldapi
      namespace: k8s-ecoysystem-apps
    spec:
      volumes:
      - name: helloworldapiSettings
        configMap:
          name: helloworldapi-appsetting
      containers:
      - name: helloworldapi
        image: justmine/helloworldapi:v2.2
        imagePullPolicy: Always
        volumeMounts:
        - name: helloworldapiSettings
          mountPath: "/"
          readonly: true
        ports:
        - containerPort: 80