apiVersion: v1
kind: Pod
metadata:
  name: helloworldapi
  labels:
    app: helloworldapi
  namespace: k8s-ecoysystem-apps
spec:
  containers:
  - name: helloworldapi
    image: justmine/helloworldapi:v1.0
    imagePullPolicy: Always
    ports:
    - containerPort: 80
