apiVersion: v1
kind: Service
metadata:
  name: helloword-api
  namespace: k8s-ecoysystem-apps
spec:
  type: NodePort
  selector:
    app: helloword-api
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80
