apiVersion: v1
kind: Pod
metadata:
  name: helloword-api
  labels:
    app: helloword-api
  namespace: k8s-ecoysystem-apps
spec:
  containers:
  - name: helloword-api
    image: justmine/hellowordapi:v1.2
    imagePullPolicy: Always
    ports:
    - containerPort: 80
