# deployment 资源配置文件声明规范注解
# 多个资源可以在一个 YAML 文件中定义，用 --- 分割。
# which version of the Kubernetes api you’re using to create this object.
# for versions before 1.9.0 use apps/v1beta2.
apiVersion: apps/v1
# 要创建的资源类型
kind: Deployment
# 该资源的元数据，name 是必需的元数据项。
metadata:
  name: nginx-deployment
  # 指定资源所属的 namespace
  namespace: kube-public
# 该 Deployment 的规格说明。
spec:
  # defines how the Deployment finds which Pods to manage.if it is unspecified, it will be defaulted to .spec.template.metadata.labels.
  selector:
    matchLabels:
      app: nginx
  # 
  progressDeadlineSeconds: 600
  # specify how many old ReplicaSets for this Deployment you want to retain
  revisionHistoryLimit: 10
  # specifies the strategy used to replace old Pods by new ones.it can be“Recreate”or“RollingUpdate”.“RollingUpdate”is the default value.
  strategy:
    type: Recreate
  # 指明保留revison的数量，以便可以随时回滚回旧版本。需要与--record配合使用。
  # --record 的作用是将当前命令记录到 revision 记录中
  revisionHistoryLimit: 10
  # tells deployment to run 2 pods matching the template
  replicas: 2 
  # create pods using pod definition in this template
  template: 
    metadata:
      # unlike pod-nginx.yaml, the name is not included in the meta data as a unique name is
      # generated from the deployment name
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        # specifies an appropriate restart container policy
        restartPolicy: Always
        image: nginx:1.7.9
        ports:
        - containerPort: 80
